devforum/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('account.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path, include, re_path
from .views import *
urlpatterns = [
    path("", PostListView.as_view(),name='home'),
    path("create/", PostCreateView.as_view(),name='post-create'),
    path("signout/", LogoutView.as_view(),name='user-logout'),
    path("detail/<int:id>", PostReplyView.as_view(),name='post-reply'),
    path("edit/<int:id>", PostEditView.as_view(),name='post-edit'),
    path("reply/<int:id>", ReplyView.as_view(),name='answer-reply'),
    path('upvote-question/',UpvoteQuestionView.as_view(),name='upvote-question'),
    path('downvote-question/',DownvoteQuestionView.as_view(),name='downvote-question'),
    path('upvote-answer/',UpvoteAnswerView.as_view(),name='upvote-answer'),
    path('downvote-answer/',DownvoteAnswerView.as_view(),name='downvote-answer'),
    path("", include("django.contrib.auth.urls")),
    path("", include("social_django.urls")),
    re_path(r'^tag-autocomplete/$',TagAutocomplete.as_view(),name='tag-autocomplete'),
]

account/models.py
from django.db import models
from .managers import CustomUserManager
from django.contrib.auth.models import AbstractUser
from datetime import datetime
import django.utils.timezone
from taggit.managers import TaggableManager

class User(AbstractUser):

    def image_upload(instance,title):
        return f'user/{instance.username}/profile/{instance.profile_pic}'
    
    def cover_pic_upload(instance,title):
        return f'user/{instance.username}/coverpic/{instance.cover_pic}'

    username = models.CharField(max_length = 50,unique = True)
    email = models.EmailField(unique = True)
    phone = models.CharField(max_length = 10,null=True)
    profile_pic = models.ImageField(upload_to= image_upload,null=True)
    cover_pic = models.ImageField(upload_to= cover_pic_upload,null=True)
    tags= TaggableManager()
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    date_joined = models.DateField(default = django.utils.timezone.now)
    updated_at =models.DateTimeField(default=datetime.now())

    object = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

post/models.py
from django.db import models
from account.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

class Question(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='question_author')
    title = models.CharField(max_length=200)
    content = RichTextUploadingField()
    tags = TaggableManager()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Answer(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='answer_author')
    question=models.ForeignKey(Question,on_delete=models.CASCADE,related_name='question_answer')
    content=RichTextUploadingField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Reply(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='reply_author')
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE,related_name='answer_reply')
    content=RichTextUploadingField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class UpvoteQuestion(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='upvote_question')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='upvote_user')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user','question',)

class DownvoteQuestion(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='downvote_question')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='downvote_user')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user','question',)

class UpvoteAnswer(models.Model):
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE,related_name='upvote_answer')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='upvote_answer_user')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user','answer',)

class DownvoteAnswer(models.Model):
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE,related_name='downvote_answer')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='downvote_answer_user')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user','answer',)

templates/pages/get_tags.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="align-center" style="width:70%;margin-left:auto;margin-right:auto;">
  <div class="card" style="margin-top:10px;">
      <div class="card-header">
        <h3>Select contents you wish to see</h3>
      </div>
      <div class="card-body">
        <form action="{% url 'select-tag' %}" method='POST'>
          {% csrf_token %}
          <p>Add a comma after each tag</p>
          <div class="mt-1 mb-2 px-3 py-2 align-center">
            {{tagform.media}}
            <div class="mt-2">{{ tagform.tags }}</div>
          </div>
          <div class="mt-1 mb-2 px-3 py-2">
            <input type='submit' class='btn btn-primary px-2 py-2' value='Submit'/>
        </div>
        </form>
      </div>
  </div>
</div>

{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/header.html' %}
<div class="container-fluid wrap mt-9">
    <div class="row mt-3">
        {% include 'partials/left_column.html' %}
        <div class="col col-lg-6 justify-content-center">
            {% for questions in posts %}
            <div class="container-fluid mt-100" style="border-radius:4px;">
              <div class="row">
                  <div class="col-md-12">
                      <div class="card mb-4">
                          <div class="card-header">
                            <div class="media flex-wrap w-100 align-items-center"> 
                                {% if questions.author.profile_pic is None %}
                                    <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% else %}
                                    <img src="{{questions.author.profile_pic}}" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% endif %}
                                <div class="media-body ml-3 mt-1"> 
                                    {% if questions.author.id == user.id %}
                                        <a href="{% url 'profile' %}">{{ questions.author.username }}</a>
                                    {% else %}
                                        <a href="{% url 'user' questions.author.username %}">{{ questions.author.username }}</a>
                                    {% endif %}
                                    <div class="text-muted small mt-1">
                                        {% if questions.duration.days == 0 %}
                                            Posted: Today
                                        {% elif questions.duration.days == 1 %}
                                            Posted: Yesterday
                                        {% else %}
                                            Posted: {{questions.duration.days}} days ago
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="pb-1">{{questions.title}}</h4>
                            <div class="flex-wrap text-small pb-2">
                                {% for tag in questions.tags %}
                                    <a href="#" class="badge px-1 py-1" style="font-size:16px;">{{tag}}</a>
                                {% endfor %}
                            </div>
                            <div>{{questions.content|safe}}</div>
                          </div>
                          <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-2">
                              <div class="px-4 pt-2">
                                <a href="javascript:void(0)" class="text-success d-inline-flex align-items-center align-middle ml-1 mr-3 upvoteq" data-question={{questions.id}}> <i class="fa fa-thumbs-up"></i>&nbsp; <span class="align-middle">{{questions.upvotes}}</span> </a>
                                <a href="javascript:void(0)" class="text-danger d-inline-flex align-items-center align-middle ml-2 mr-2 downvoteq" data-question={{questions.id}}> <i class="fa fa-thumbs-down"></i>&nbsp; <span class="align-middle">{{questions.downvotes}}</span> </a>
                                <span href="#" class="text-muted d-inline-flex align-items-center align-middle ml-3"> <i class="fa fa-comments"></i>&nbsp; <span class="align-middle">{{questions.answers}}</span> </span> </div>
                              <div class="px-4 pt-2"><a href="{% url 'post-reply' questions.id %}" class="btn btn-primary btn-sm">Answer<i class="fa fa-comment mx-2"></i></a> </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
            {% endfor %}
        </div>
        <div class="col col-md-3" style="border-radius:4px;">
            <div class="card d-flex">
                <div class="card-body">
                    <h3 class="mb-3">Suggested Users</h3>
                    {% for item_user in users %}
                        <div class="py-2 px-2 mx-2 mt-2 d-flex">
                            {% if item_user.profile_pic is None %}
                                <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:20%; height: 20%;" alt="">
                            {% else %}
                                <img src="{{item_user.profile_pic}}" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:20%; height: 20%;" alt="">
                            {% endif %}
                            <div class="d-block ml-2 justify-content-center">
                                {% if item_user.id == user.id %}
                                    <a href="{% url 'profile' %}">{{ item_user.username }}</a>
                                {% else %}
                                    <a href="{% url 'user' item_user.username %}">{{ item_user.username }}</a>
                                {% endif %}
                                <div>
                                    {% for tag in item_user.tags %}
                                        <div class="badge px-1 py-1">{{tag}}</div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/pages/post_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% include 'partials/header.html' %}
<div class="container-fluid wrap py-3">
    <div class="row mt-3" style="border-radius:4px;">

        {% include 'partials/left_column.html' %}

        <div class="col col-lg-9 d-flex justify-content-center">
            <div class="container-fluid mt-100">
                <div class="card">
                    <div class="card-body">
                        <form action="" method ="POST">
                            {% csrf_token %}
                            <div class="mb-4 px-3 py-1">
                                <p class="mt-2 font-weight-bold" style="font-size:18px;">Title:</p>
                                <small class="text-muted" >Be specific and imagine you're asking a question to another person.</small>
                                <div class="my-1">{{ form.title }}</div>
                            </div>
                            <div class="mt-1 mb-2 px-3 py-2 align-center">
                                <p class="mt-2 text-xl font-weight-bold" style="font-size:18px;">Details of your problem and what you have you tried/your expectations:</p>
                                <small class="text-muted">Introduce Your Problem along with your attempts and your expected outcome.</small>
                                {{ form.media }}
                                <div class="mt-2">{{ form.content }}</div>
                            </div>
                            <div class="mt-1 mb-2 px-3 py-2 align-center">
                                <p class="mt-2 font-weight-bold" style="font-size:18px;">Add tags to your question:</p>
                                <div class="mt-2">{{ form.tags }}</div>
                            </div>
                            <div class="mt-1 mb-2 px-3 py-2">
                                <input type='submit' class='btn btn-primary px-2 py-2' value='Edit Question' id='edit'/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

templates/pages/post_threads.html
{% extends 'base.html' %}
{% block content %}

{% include 'partials/header.html' %}
<div class="container-fluid wrap">
    <div class="row mt-3">
        {% include 'partials/left_column.html' %}
        <div class="col col-lg-8 justify-content-center">
            <div class="container-fluid mt-100" style="border-radius:4px;">
              <div class="row">
                  <div class="col-md-12">
                      <div class="card mb-4">
                          <div class="card-header">
                              <div class="media flex-wrap w-100 align-items-center"> 
                                {% if question.author.profile_pic is None %}
                                    <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% else %}
                                    <img src="{{question.author.profile_pic}}" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% endif %}
                                <div class="media-body ml-3 mt-1"> 
                                    {% if user.id == answer.author.id %}
                                        <a href="{% url 'profile' %}" data-abc="true">{{question.author.username}}</a>
                                    {% else %}
                                        <a href="{% url 'user' question.author.username %}" data-abc="true">{{question.author.username}}</a>
                                    {% endif %}
                                    <div class="text-muted small mt-1">
                                        {% if question.duration.days == 0 %}
                                            Posted: Today
                                        {% elif question.duration.days == 1 %}
                                            Posted: Yesterday
                                        {% else %}
                                            Posted: {{question.duration.days}} days ago
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="pb-1">{{question.title}}</h4>
                            <div class="flex-wrap text-small pb-2">
                                {% for tag in question.tags %}
                                    <a href="#" class="badge px-1 py-1" style="font-size:16px;">{{tag}}</a>
                                {% endfor %}
                            </div>
                            <div>{{question.content|safe}}</div>
                          </div>
                          <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-2">
                              <div class="px-4 pt-2">
                                <a href="javascript:void(0)" class="text-success d-inline-flex align-items-center align-middle ml-1 mr-3 upvoteq" data-question={{question.id}}> <i class="fa fa-thumbs-up"></i>&nbsp; <span class="align-middle">{{question.upvotes}}</span> </a>
                                <a href="javascript:void(0)" class="text-danger d-inline-flex align-items-center align-middle ml-2 mr-2 downvoteq" data-question={{question.id}}> <i class="fa fa-thumbs-down"></i>&nbsp; <span class="align-middle">{{question.downvotes}}</span> </a>
                                <span class="text-muted d-inline-flex align-items-center align-middle ml-3"> <i class="fa fa-comments"></i>&nbsp; <span class="align-middle">{{question.answers}}</span> </span> </div>
                          </div>
                      </div>
                  </div>
              </div>
              {% for answer in question.question_answer %}
              <div class="row mt-3">
                  <div class="col col-md-12">
                        <div class="card">
                          <div class="card-header">
                            <div class="media flex-wrap w-100 align-items-center">
                                {% if answer.author.profile_pic is None %}
                                    <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% else %}
                                    <img src="{{answer.author.profile_pic}}" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                {% endif %}
                                <div class="media-body ml-3 mt-1"> 
                                    {% if user.id == answer.author.id %}
                                        <a href="{% url 'profile' %}" data-abc="true">{{answer.author.username}}</a>
                                    {% else %}
                                        <a href="{% url 'user' answer.author.username %}" data-abc="true">{{answer.author.username}}</a>
                                    {% endif %}
                                    <div class="text-muted small mt-1">
                                        {% if answer.duration.days == 0 %}
                                            Posted: Today
                                        {% elif answer.duration.days == 1 %}
                                            Posted: Yesterday
                                        {% else %}
                                            Posted: {{answer.duration.days}} days ago
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                          </div>
                          <div class="card-body">
                          <div>{{answer.content|safe}}</div>
                        </div>
                        <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-2">
                            <div class="px-4 pt-2">
                              <a href="javascript:void(0)" class="text-success d-inline-flex align-items-center align-middle ml-1 mr-3 upvote-answer" data-answer={{answer.id}}> <i class="fa fa-thumbs-up"></i>&nbsp; <span class="align-middle">{{answer.upvotes}}</span> </a>
                              <a href="javascript:void(0)" class="text-danger d-inline-flex align-items-center align-middle ml-2 mr-2 downvote-answer" data-answer={{answer.id}}> <i class="fa fa-thumbs-down"></i>&nbsp; <span class="align-middle">{{answer.downvotes}}</span> </a>
                              <span class="text-muted d-inline-flex align-items-center align-middle ml-3"> <i class="fa fa-comments"></i>&nbsp; <span class="align-middle">{{answer.replies}}</span> </span> </div>
                              <div class="px-4 pt-2"><a href="{% url 'answer-reply' answer.id %}" class="btn btn-primary btn-sm"><i class="fa fa-reply mr-2"></i>Reply</a> </div>
                            </div>
                      </div>
                  </div>
              </div>
              {% empty %}
              <div class="row mt-3">
                <div class="col col-md-12">
                    <div class="card text-center">
                        <h4 class="my-2 py-2">No Answers to the question</h4>
                    </div>
                </div>
              </div>
              {% endfor %}
              <div class="row mt-3">
                <div class="col col-lg-12">
                    <div class="card" style = "width:110%;">
                        <h3 class="card-header">Submit an Answer to the question</h3>
                        <div class="card-body">
                            <form action="{% url 'post-reply' question.id %}" method='POST'>
                                {% csrf_token %}
                                {{answerform.media}}
                                {{answerform.content}}
                                <div class="mt-1 mb-2 px-3 py-2">
                                    <input type='submit' class='btn btn-primary px-2 py-2' value='Submit Your Answer'/>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/pages/search_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/header.html' %}
<div class="container-fluid wrap py-3">
    <div class="row mt-3" style="border-radius:4px;">

        {% include 'partials/left_column.html' %}

        <div class="col col-lg-9 d-flex justify-content-center">
            <div class="container-fluid mt-100">
                <div class="card my-2">
                    <div class="card-header">
                        <h3>Users</h3>
                    </div>
                    <div class="card-body">
                        {% for users in user_list %}
                            <div>
                                <div class="d-flex w-100">
                                    {% if users.profile_pic %}
                                        <img src={{users.profile_pic}} alt="" style="width:8%;" class="rounded-circle">
                                    {% else %}
                                        <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="rounded-circle" style="width:8%;" alt="">
                                    {% endif %}
                                    {% if users.id == user.id %}
                                        <div class="mx-4 mt-3"style="font-size:18px;"><a href="{% url 'profile' %}">{{users.username}}</a></div>
                                    {% else %}
                                        <div class="mx-4 mt-3"style="font-size:18px;"><a href="{% url 'user' users.username %}">{{users.username}}</a></div>
                                    {% endif %}
                                </div>
                            </div>
                        {% empty %}
                        <div>
                            <span>your search yielded no result</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card my-2">
                    <div class="card-header">
                        <h3>Questions</h3>
                    </div>
                    <div class="card-body" >
                        {% for questions in question_list %}
                            <div class="card my-2">
                                <div class="card-header">
                                    <div class="media flex-wrap w-100 align-items-center">
                                        {% if not questions.author.profile_pic %}
                                            <img src="https://pixlok.com/wp-content/uploads/2021/03/default-user-profile-picture.jpg" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                        {% else %}
                                            <img src="{{questions.author.profile_pic}}" class="d-block img-fluid img-thumbnail rounded-circle mr-2" style="width:10%; height: 10%;" alt="">
                                        {% endif %}
                                        <div class="media-body media-body ml-3 mt-1">
                                            {% if questions.author.id == user.id %}
                                                <a href="{% url 'profile' %}">{{ questions.author.username }}</a>
                                            {% else %}
                                                <a href="{% url 'user' questions.author.username %}">{{ questions.author.username }}</a>
                                            {% endif %}
                                            <div class="text-muted small mt-1">
                                                {% if questions.duration.days == 0 %}
                                                    Posted: Today
                                                {% elif questions.duration.days == 1 %}
                                                    Posted: Yesterday
                                                {% else %}
                                                    Posted: {{questions.duration.days}} days ago
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <h4 class="pb-1">{{questions.title}}</h4>
                                    <div class="flex-wrap text-small pb-2">
                                        {% for tag in questions.tags %}
                                            <a href="#" class="badge px-1 py-1" style="font-size:16px;">{{tag}}</a>
                                        {% endfor %}
                                    </div>
                                    <div>{{questions.content|safe}}</div>
                                </div>
                                <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-2">
                                    <div class="px-4 pt-2">
                                      <a href="javascript:void(0)" class="text-success d-inline-flex align-items-center align-middle ml-1 mr-3 upvoteq" data-question={{questions.id}}> <i class="fa fa-thumbs-up"></i>&nbsp; <span class="align-middle">{{questions.upvotes}}</span> </a>
                                      <a href="javascript:void(0)" class="text-danger d-inline-flex align-items-center align-middle ml-2 mr-2 downvoteq" data-question={{questions.id}}> <i class="fa fa-thumbs-down"></i>&nbsp; <span class="align-middle">{{questions.downvotes}}</span> </a>
                                      <span href="#" class="text-muted d-inline-flex align-items-center align-middle ml-3"> <i class="fa fa-comments"></i>&nbsp; <span class="align-middle">{{questions.answers}}</span> </span> </div>
                                    <div class="px-4 pt-2"><a href="{% url 'post-reply' questions.id %}" class="btn btn-primary btn-sm">Answer<i class="fa fa-comment mx-2"></i></a> </div>
                                </div>
                            </div>
                            {% empty %}
                            <div>
                                <span>your search yielded no result</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}